# Generated by Django 2.2.20 on 2022-04-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20220404_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_date',
            field=models.DateField(),
        ),
    ]
